# -*- coding: utf-8 -*-
"""ES_File

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bt5JpCI57QmvTUIEgbpoDcDKoA_BA83T
"""

#ES Question3
import numpy as np
def ES(losses, confidence=None, VaR=None, use_PnL=False):
  losses = np.asarray(losses)
  if VaR is None:
    VaR = np.percentile(losses, 100 * confidence)
  excess_losses = losses[losses > VaR]
  es_value = np.mean(excess_losses)
  return es_value