# -*- coding: utf-8 -*-
"""VaR_File

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bt5JpCI57QmvTUIEgbpoDcDKoA_BA83T
"""

#VaR Question2
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
def VaR(r, confidence, principal = 1):
  alpha = (1 - confidence) * 100
  var_percentile = np.percentile(r, alpha)
  var = abs(var_percentile)
  out = principal * var
  return out

def percent_var(r, confidence):
    plt.hist(r, bins=50, alpha=0.75)
    plt.xlabel('Returns')
    plt.ylabel('Frequency')
    plt.title('VaR')
    alpha = confidence
    out = np.percentile(r, (1 - alpha) * 100)
    return abs(out)