# -*- coding: utf-8 -*-
"""YFinance_File

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bt5JpCI57QmvTUIEgbpoDcDKoA_BA83T
"""

#Get Return Question1
def YahooData2returns(YahooData):
  def get_stock_data(YahooData):
    data = yf.download(YahooData)
    prices = data['Adj Close'] if 'Adj Close' in data.columns else data['Close']
    return prices
  prices = get_stock_data(YahooData)
  pricevec = prices.values
  n = len(pricevec)
  ratiovec = pricevec[1:n] / pricevec[:n-1]
  returns = ratiovec - 1
  return returns


ticker = 'GS'
returns = YahooData2returns(ticker)
print (returns)

df = pd.DataFrame(returns, index=data.index[1:], columns=['Daily Return'])
df